name: Build Scratch Image

on:
  push:
    branches:
      - main
    paths:
      - "scratch/**"
  pull_request:
    paths:
      - "scratch/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-scratch
      cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != github.event.repository.default_branch }}
    strategy:
      matrix:
        debian_version: [bookworm]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if: github.ref_name == github.event.repository.default_branch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (QEMU)
        if: github.ref_name == github.event.repository.default_branch
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-${{ matrix.debian_version }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ matrix.debian_version }},suffix=,enable={{is_default_branch}}
            type=raw,value=latest,suffix=,enable=${{ github.ref_name == github.event.repository.default_branch && matrix.debian_version == 'bookworm' }}
            type=edge,branch=main
          images: |
            ghcr.io/${{ github.repository }}/scratch

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: scratch
          push: ${{ (github.event_name == 'push' && (github.ref_name == github.event.repository.default_branch || github.ref_type == 'tag')) || github.event_name == 'pull_request' }}
          platforms: ${{ github.ref_name == github.event.repository.default_branch && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true
          build-args: |
            DEBIAN_VERSION=${{ matrix.debian_version }}
